avatar: false
cookies:
  ? ''
  : douyin.com
  DiscoverFeedExposedAd: '%7B%7D'
  IsDouyinActive: 'true'
  SEARCH_RESULT_LIST_TYPE: '%22single%22'
  SEARCH_UN_LOGIN_PV_CURR_DAY: '%7B%22date%22%3A1766866503879%2C%22count%22%3A9%7D'
  SelfTabRedDotControl: '%5B%5D'
  UIFID: 3336119d6ecc0f2721002588cf880fbc4753b1582d4c54bc5f80aa9273463f02f96d633a5f3ac91bfb0db74e6f390c196c524ca67db8d6636517722f0d4d836bfcbcce1f67fcdb1b26648c6228d4f0ac9257eb08e5e10de4ddab680cb6b61fbaf4f424482660e5e1378694385881f0db007480c32c3bcc8075106dc18051ef4e761e8b297f7981843bf9657caf1fc1359eb5ed51d9814770b6ac119c34997815
  UIFID_TEMP: 3336119d6ecc0f2721002588cf880fbc4753b1582d4c54bc5f80aa9273463f0264886032bcab510bc8e584a49a10cbd6e8ac5d1055f2edf377ca78584c20bbe959187d2c127b458662562121f8209330
  __ac_signature: _02B4Z6wo00f01Yqp-HgAAIDCbtLC2ZivFE2KifzAAAv52d
  __druidClientInfo: JTdCJTIyY2xpZW50V2lkdGglMjIlM0EwJTJDJTIyY2xpZW50SGVpZ2h0JTIyJTNBODk1JTJDJTIyd2lkdGglMjIlM0EwJTJDJTIyaGVpZ2h0JTIyJTNBODk1JTJDJTIyZGV2aWNlUGl4ZWxSYXRpbyUyMiUzQTElMkMlMjJ1c2VyQWdlbnQlMjIlM0ElMjJNb3ppbGxhJTJGNS4wJTIwKFdpbmRvd3MlMjBOVCUyMDEwLjAlM0IlMjBXaW42NCUzQiUyMHg2NCklMjBBcHBsZVdlYktpdCUyRjUzNy4zNiUyMChLSFRNTCUyQyUyMGxpa2UlMjBHZWNrbyklMjBDaHJvbWUlMkYxNDIuMC4wLjAlMjBTYWZhcmklMkY1MzcuMzYlMjIlN0Q=
  __security_mc_1_s_sdk_cert_key: ac42945e-4c0c-bfa6
  __security_mc_1_s_sdk_crypt_sdk: 84f4516a-4282-9a36
  __security_mc_1_s_sdk_sign_data_key_web_protect: d7b428a7-4150-b94f
  __security_server_data_status: '1'
  _bd_ticket_crypt_cookie: cadedb13fe4e8c0931572dc78342f180
  _bd_ticket_crypt_doamin: '2'
  architecture: amd64
  bd_ticket_guard_client_data: eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCSEcrMGZHWXFTb1BoL1ZYdHJzVXpkUWo3Q3pTU2NvLzdiYy9xNVJ5SGo0UDR5enBhM0VMcDV0WUhYMDFEdC9iQmlweXJINndkV01HZ1hZQUd0WlF1RGc9IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoyfQ%3D%3D
  bd_ticket_guard_client_data_v2: eyJyZWVfcHVibGljX2tleSI6IkJIRyswZkdZcVNvUGgvVlh0cnNVemRRajdDelNTY28vN2JjL3E1UnlIajRQNHl6cGEzRUxwNXRZSFgwMUR0L2JCaXB5ckg2d2RXTUdnWFlBR3RaUXVEZz0iLCJ0c19zaWduIjoidHMuMi5lMmU4NmI2N2EyNjkzN2U2NDQxNWU1YmQwM2UyYjk0YjExMWI5YmRhMzM1YmJlZmQ5ZDI1MzdmOTA0MWQ1MWM0YzRmYmU4N2QyMzE5Y2YwNTMxODYyNGNlZGExNDkxMWNhNDA2ZGVkYmViZWRkYjJlMzBmY2U4ZDRmYTAyNTc1ZCIsInJlcV9jb250ZW50Ijoic2VjX3RzIiwicmVxX3NpZ24iOiJ3T2V5cmhTY3I2Y1RSdFBsVHFldXdCMms2bmNyNUV1T3ZZQ0h5eXc0RkR3PSIsInNlY190cyI6IiN2aXZDWEV2a2tZWUM3SDZtQ2daNXlRQnRQb3kyb3RwK3VBdWYwT2VUN2Ezbi9ZN2t1alJ1azNMcXRFYjMifQ%3D%3D
  bd_ticket_guard_client_web_domain: '2'
  bit_env: Y7dCj3HjKVOdFgwr38QjVmQwxsH0aNkqbT-VrNN8SftF9cfYNl8gCZ9WuSbta5IPWgjs1GxD7yPuCjWJTp-7Uwap3N_q9c1y1Unsthbt5oZNpvtIjSx1v9ucnUcAO04SSdotRxoGyvH7-QbHaH5lM_twI8WxnEwhPZNezdmRuXcPr3EaJwI4vDp1JtXJ8oi8NS7kRbchanH_toMrrvc7n0KoaWRIMVj8dZ573XhMRhn48fDnPTE7Y5m8NY9jzCxVhM3rQEO2UeXHKClQXRRG6uUDOKvvWs-3fY5VUAk4OjCQk-mbZXLFuIYb-O1kwpx8PexAFLJK5pI9qpLDZiZnYQ7SEVS7VSAKcn0fH6ygRTut4UXsr_iAZEZvg_zyhknM-7Bq7S48cJQKfdCNGsIIu5C1oNXYMfdr-ODOGi8t43yQ4G8uQXn0cQku71dxDF0QiSP09JFmmeu2vtA_BK_nwVvUXAnePdC_GoUTfxTRava2xOxIo7mLYbA_xn6vr6K9
  biz_trace_id: 71fea582
  csrf_session_id: 0e4b9b9a4598ade881834a5611fd5533
  d_ticket: fc251a8a77702b0837fb1e64101cba78717bd
  device_web_cpu_core: '16'
  device_web_memory_size: '8'
  download_guide: '%223%2F20251224%2F1%22'
  dy_sheight: '1080'
  dy_swidth: '1920'
  enter_pc_once: '1'
  fpk1: U2FsdGVkX186vyUEpigAUkxEgG1Lh52utf3UmtRSHBWzeZ6vF6rmnKE7+i5zsdc9jXl0+G5dIPpkMBGTou9g8A==
  fpk2: 3c9fc7ddec9b58823c1c96756dbd45d8
  gulu_source_res: eyJwX2luIjoiZDg5ZGRhM2JhYWRjMGY2Yzk3MDk4ZWM2Nzk1MTFlZjJjMGMwZTFmMDUyZTBlMTI5MzRkNDg2YzhlM2JjYmZkOSJ9
  hevc_supported: 'true'
  home_can_add_dy_2_desktop: '%221%22'
  is_dash_user: '1'
  is_staff_user: 'false'
  login_time: '1766935473399'
  my_rd: '2'
  n_mh: -cWA8CgapSaVjJPuFiN-n1vSgrRdvjJm5SmIj3iy_BA
  odin_tt: 80fbfbbe9e906bc0805437084983c841fc647829bce470cc4c34e5d5ee33b8627e1e7ef9206739c5a50b7dab186fffa77be509bff6a6f610f2fb2ccb656f11f7
  passport_assist_user: Cj_HVTw-qI-ofLxXNfjpBaI1t7TKEYavWu0zkSaeU_MkTKYhIIJGXZBGj4Ud8rDYCxEsMFLwljTdgzsuBeo7eMYaSgo8AAAAAAAAAAAAAE_ixOodASob6_wmwkxVeDWynJwTJJfDcXrY3hjX-0dPfVGxiKxhWue1OS9xtp25um2yEJm1hQ4Yia_WVCABIgEDXI-Lyw%3D%3D
  passport_auth_mix_state: iydtdyemz2rvddusdgfd6256fni5ulon
  passport_auth_status: 1c516908019de0f03b3d0e65973283ed%2Cb2b202e1d58f47c14d78cb6b4eb9b11e
  passport_auth_status_ss: 1c516908019de0f03b3d0e65973283ed%2Cb2b202e1d58f47c14d78cb6b4eb9b11e
  passport_csrf_token: 590da96e45b50a3adddaa9a6fba223b6
  passport_csrf_token_default: 590da96e45b50a3adddaa9a6fba223b6
  passport_mfa_token: CjbPfcc33LwGDpgqW9Pe32xVIEN78wkjN17WpuQbSO%2FTDcKDYe8gWqlo1YAQBLVJxA90SruiGFkaSgo8AAAAAAAAAAAAAE%2FiQS7dozEqVT9%2Be7Ujt2tJB6O9BDjVo2ltqhZJzFJwqG4ovBHVi96ZsepmujtATRGeEJm1hQ4Y9rHRbCACIgEDEMybag%3D%3D
  playRecommendGuideTagCount: '2'
  publish_badge_show_info: '%220%2C0%2C0%2C1766934791305%22'
  record_force_login: '%7B%22timestamp%22%3A1766864166025%2C%22force_login_video%22%3A220%2C%22force_login_live%22%3A2%2C%22force_login_direct_video%22%3A0%7D'
  s_v_web_id: verify_mjf4tfg7_6HqjWea9_vHMk_4UNb_9KOA_Capf329msXzC
  sdk_source_info: 7e276470716a68645a606960273f276364697660272927676c715a6d6069756077273f276364697660272927666d776a68605a607d71606b766c6a6b5a7666776c7571273f275e58272927666a6b766a69605a696c6061273f27636469766027292762696a6764695a7364776c6467696076273f275e582729277672715a646971273f2763646976602729277f6b5a666475273f2763646976602729276d6a6e5a6b6a716c273f2763646976602729276c6b6f5a7f6367273f27636469766027292771273f27333c323c3632333c3c33333234272927676c715a75776a716a666a69273f2763646976602778
  session_tlb_tag: sttt%7C16%7CRlQMa6WDnjv6OGwfjiIP8f________-tKBbjG0fNFYcSEnLaFr8UvnQ0RrBYDY5CDS8YuVkk7fs%3D
  sessionid: 46540c6ba5839e3bfa386c1f8e220ff1
  sessionid_ss: 46540c6ba5839e3bfa386c1f8e220ff1
  sid_guard: 46540c6ba5839e3bfa386c1f8e220ff1%7C1766935472%7C5184000%7CThu%2C+26-Feb-2026+15%3A24%3A32+GMT
  sid_tt: 46540c6ba5839e3bfa386c1f8e220ff1
  sid_ucp_v1: 1.0.0-KDc2ZGFlYmYwNzBjZWEyNDA1ZmQ0ODQ5YmQ5YWZlYjNiZmU0OTc3YjcKIAjX5NCj0awGELCXxcoGGO8xIAwwh4_FygY4AkDxB0gEGgJobCIgNDY1NDBjNmJhNTgzOWUzYmZhMzg2YzFmOGUyMjBmZjE
  ssid_ucp_v1: 1.0.0-KDc2ZGFlYmYwNzBjZWEyNDA1ZmQ0ODQ5YmQ5YWZlYjNiZmU0OTc3YjcKIAjX5NCj0awGELCXxcoGGO8xIAwwh4_FygY4AkDxB0gEGgJobCIgNDY1NDBjNmJhNTgzOWUzYmZhMzg2YzFmOGUyMjBmZjE
  strategyABtestKey: '%221766986411.659%22'
  stream_player_status_params: '%22%7B%5C%22is_auto_play%5C%22%3A0%2C%5C%22is_full_screen%5C%22%3A0%2C%5C%22is_full_webscreen%5C%22%3A0%2C%5C%22is_mute%5C%22%3A1%2C%5C%22is_speed%5C%22%3A1%2C%5C%22is_visible%5C%22%3A0%7D%22'
  stream_recommend_feed_params: '%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1920%2C%5C%22screen_height%5C%22%3A1080%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A16%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A10%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A50%7D%22'
  theme: '%22light%22'
  totalRecommendGuideTagCount: '17'
  ttwid: 1%7CDjzvgreaWB1Zi3neldUf3SMu56ms1qfNIbK3Jke7s6Y%7C1766986411%7Cea6dc6a6b75c5801b3de8372bd24ef1f4ec3dbe3f7e3f287789d08896f30a743
  uid_tt: 64db8d5f047360d27dc33e45895a5b0c
  uid_tt_ss: 64db8d5f047360d27dc33e45895a5b0c
  volume_info: '%7B%22isMute%22%3Atrue%2C%22isUserMute%22%3Afalse%2C%22volume%22%3A0.197%7D'
  x-web-secsdk-uid: d510a087-42c5-466e-88bc-91adf3417a3a
  xgplayer_device_id: '39060658691'
  xgplayer_user_id: '172928144001'
cover: true
end_time: ''
json: true
link:
- https://www.douyin.com/user/MS4wLjABAAAA0d0eUrmvkM8u07ZvlThOg1E121OcRU_V6vqYBb-3L6myVZIgsU3lKP32jNrfPESS
mode:
- post
music: true
number:
  like: 0
  post: 2
path: ./Downloaded/
retry_times: 3
start_time: ''
thread: 5
